---
- name: apt | install notebook packages
  apt: name={{ item }} state=present update_cache=true
  loop:
    # mainly for the native dependencies
    - python3-matplotlib
    - python3-scipy
    # actually needed
    - python3
    - python3-pip

- name: apt | install the venv package if there
  apt: name={{ item }} state=present
  loop:
    - python3-venv
  ignore_errors: yes