---
- include: user.yml
  tags:
    - user
- include: apt.yml
  tags:
    - apt
- include: main_jupyter.yml
  become: true
  become_user: '{{ notebook.user }}'
- include: service.yml
  tags:
    - service
