---
- include: apt.yml
  tags:
    - apt
- include: venv.yml
  tags:
    - pip
- include: pip.yml
  tags:
    - pip
- include: config.yml
  tags:
    - config
- include: service.yml
  tags:
    - service
