---
# Apply OS upgrades and reboot the VMs
- hosts: servers
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
    - config.yml
  roles:
    - { role: debops.unattended_upgrades, tags: ["unattended_upgrades"]}
    - { role: notebook, when: install_notebook }
